In [1]:
import pandas as pd
import numpy as np

In [2]:
enbie = pd.read_csv("NBA.csv")
enbie.head()

,Unnamed: 0,player_name,team_abbreviation,age,player_height,player_weight,college,country,draft_year,draft_round,...,pts,reb,ast,net_rating,oreb_pct,dreb_pct,usg_pct,ts_pct,ast_pct,season
0,0,Chris Robinson,VAN,23.0,195.58,90.71840,Western Kentucky,USA,1996,2,...,4.6,1.7,1.6,-11.4,0.039,0.088,0.155,0.486,0.156,1996-97
1,1,Matt Fish,MIA,27.0,210.82,106.59412,North Carolina-Wilmington,USA,1992,2,...,0.3,0.8,0.0,-15.1,0.143,0.267,0.265,0.333,0.000,1996-97
2,2,Matt Bullard,HOU,30.0,208.28,106.59412,Iowa,USA,Undrafted,Undrafted,...,4.5,1.6,0.9,0.9,0.016,0.115,0.151,0.535,0.099,1996-97
3,3,Marty Conlon,BOS,29.0,210.82,111.13004,Providence,USA,Undrafted,Undrafted,...,7.8,4.4,1.4,-9.0,0.083,0.152,0.167,0.542,0.101,1996-97
4,4,Martin Muursepp,DAL,22.0,205.74,106.59412,None,USA,1996,1,...,3.7,1.6,0.5,-14.5,0.109,0.118,0.233,0.482,0.114,1996-97

In [3]:
aibiel = pd.DataFrame({
    "Name" : ["Andakara Prastawa Dyaksa", "Reggie Mononimbar", "Hardianus Lakudu", 
              "Kevin Yonas Sitorus", "Arki Dikania Wisnu", "Laurentius Steven Oei", 
              "Mei Joni", "Vincent Rivaldi", "Hardian Wicaksono", "Brandon Jawato"], 
    "Club" : ["Pelita Jaya Bakrie", "Pelita Jaya Bakrie", "Satria Muda Pertamina Jakarta", 
              "Satria Muda Pertamina Jakarta", "Satria Muda Pertamina Jakarta", "Satria Muda Pertamina Jakarta", 
              "Stapac", "Stapac", "Pacific Caesar Surabaya", "Louvre Surabaya"],
    "Country" : ["Indonesia","Indonesia","Indonesia","Indonesia","Indonesia",
                 "Indonesia","Indonesia","Indonesia","Indonesia","Indonesia",],
    "Age" : [24, 21, 23, 26, 20, 21, 25, 23, 21, 24],
    "Height" : [190, 185, 178, 185, 183, 191, 188, 179, 177, 182],
    "Weight" : [90, 86, 83, 75, 80, 85, 90, 87, 80, 85],
    "Avg Points" : [7, 6, 10, 11, 5, 4, 7, 1, 9, 6],
    "Avg Rebounds" : [6, 3, 3, 4, 2, 10, 5, 2, 8, 5]
})
aibiel

,Name,Club,Country,Age,Height,Weight,Avg Points,Avg Rebounds
0,Andakara Prastawa Dyaksa,Pelita Jaya Bakrie,Indonesia,24,190,90,7,6
1,Reggie Mononimbar,Pelita Jaya Bakrie,Indonesia,21,185,86,6,3
2,Hardianus Lakudu,Satria Muda Pertamina Jakarta,Indonesia,23,178,83,10,3
3,Kevin Yonas Sitorus,Satria Muda Pertamina Jakarta,Indonesia,26,185,75,11,4
4,Arki Dikania Wisnu,Satria Muda Pertamina Jakarta,Indonesia,20,183,80,5,2
5,Laurentius Steven Oei,Satria Muda Pertamina Jakarta,Indonesia,21,191,85,4,10
6,Mei Joni,Stapac,Indonesia,25,188,90,7,5
7,Vincent Rivaldi,Stapac,Indonesia,23,179,87,1,2
8,Hardian Wicaksono,Pacific Caesar Surabaya,Indonesia,21,177,80,9,8
9,Brandon Jawato,Louvre Surabaya,Indonesia,24,182,85,6,5

In [4]:
enbie.isnull().sum()

Unnamed: 0           0
player_name          0
team_abbreviation    0
age                  0
player_height        0
player_weight        0
college              0
country              0
draft_year           0
draft_round          0
draft_number         0
gp                   0
pts                  0
reb                  0
ast                  0
net_rating           0
oreb_pct             0
dreb_pct             0
usg_pct              0
ts_pct               0
ast_pct              0
season               0
dtype: int64

In [5]:
enbieNeed = enbie[["age", "player_height", "player_weight", "pts", "reb"]]
enbieNeed

       age  player_height  player_weight   pts  reb
0     23.0         195.58       90.71840   4.6  1.7
1     27.0         210.82      106.59412   0.3  0.8
2     30.0         208.28      106.59412   4.5  1.6
3     29.0         210.82      111.13004   7.8  4.4
4     22.0         205.74      106.59412   3.7  1.6
...    ...            ...            ...   ...  ...
9556  29.0         200.66       97.52228   1.5  3.0
9557  23.0         193.04       83.91452  12.8  4.7
9558  25.0         220.98      120.20188   4.0  5.5
9559  23.0         210.82      108.86208   8.2  7.0
9560  30.0         203.20      102.05820  15.7  6.5

[9561 rows x 5 columns]

In [6]:
conwtd = enbie[(enbie['age'] <= 25) & (enbie['player_height'] >= 180) & (enbie['player_weight'] <= 90) 
                   & (enbie['pts'] >= 6) & (enbie['reb'] >= 3)]
conwtd.index.values

array([ 105,  290,  432,  659,  835,  874, 1018, 1032, 1062, 1135, 1141,
       1332, 1351, 1436, 1515, 1516, 1720, 1727, 1748, 1951, 2004, 2018,
       2047, 2101, 2114, 2143, 2203, 2259, 2394, 2398, 2484, 2544, 2551,
       2631, 2704, 2836, 2840, 2873, 2984, 3010, 3081, 3159, 3329, 3376,
       3389, 3441, 3449, 3529, 3558, 3573, 3704, 3717, 3721, 3830, 3994,
       4036, 4039, 4121, 4124, 4252, 4267, 4271, 4374, 4385, 4422, 4482,
       4483, 4502, 4528, 4547, 4556, 4613, 4624, 4633, 4665, 4775, 4800,
       4924, 5070, 5154, 5156, 5164, 5229, 5274, 5292, 5293, 5383, 5390,
       5512, 5521, 5522, 5548, 5587, 5609, 5675, 5743, 5747, 5820, 5914,
       5952, 6001, 6014, 6040, 6098, 6183, 6272, 6277, 6304, 6343, 6360,
       6408, 6409, 6441, 6450, 6542, 6639, 6710, 6810, 6822, 6871, 6926,
       6959, 6979, 7009, 7040, 7059, 7073, 7091, 7184, 7199, 7305, 7306,
       7342, 7365, 7369, 7389, 7491, 7521, 7601, 7643, 7654, 7655, 7720,
       7739, 7821, 7827, 7900, 7904, 7935, 7983, 8003, 8022, 8051, 8060,
       8131, 8177, 8191, 8289, 8321, 8432, 8447, 8453, 8470, 8478, 8586,
       8591, 8603, 8705, 8718, 8755, 8766, 8779, 8891, 8894, 8935, 8986,
       8992, 8999, 9031, 9078, 9129, 9159, 9174, 9234, 9276, 9333, 9345,
       9371, 9485, 9522, 9557])

In [7]:
targetList = []
targetIndex = conwtd.index.values

for i in range(len(enbieNeed)):
    if i in targetIndex:
        targetList.append(1)
    else:
        targetList.append(0)

enbieNeed["target"] = pd.DataFrame(targetList)
enbieNeed

<ipython-input-7-f4b5689029d7>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  enbieNeed["target"] = pd.DataFrame(targetList)

       age  player_height  player_weight   pts  reb  target
0     23.0         195.58       90.71840   4.6  1.7       0
1     27.0         210.82      106.59412   0.3  0.8       0
2     30.0         208.28      106.59412   4.5  1.6       0
3     29.0         210.82      111.13004   7.8  4.4       0
4     22.0         205.74      106.59412   3.7  1.6       0
...    ...            ...            ...   ...  ...     ...
9556  29.0         200.66       97.52228   1.5  3.0       0
9557  23.0         193.04       83.91452  12.8  4.7       1
9558  25.0         220.98      120.20188   4.0  5.5       0
9559  23.0         210.82      108.86208   8.2  7.0       0
9560  30.0         203.20      102.05820  15.7  6.5       0

[9561 rows x 6 columns]

In [8]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import roc_auc_score

In [27]:
def scoring(model, paramXTrain, paramYTrain, paramXTest, paramYTest):
    model.fit(paramXTrain, paramYTrain)
    yPred = model.predict(paramXTest)
    print("Model: ", model)
    print("Best Parameters: ", model.best_params_)
    print("Balanced Accuracy Score: ", balanced_accuracy_score(paramYTest, yPred))
    print("Precision Score: ", precision_score(paramYTest, yPred))
    print("Recall: ", recall_score(paramYTest, yPred))
    print("F1 Score: ", f1_score(paramYTest, yPred))
    print("ROC AUC Score: ", roc_auc_score(paramYTest, yPred))
    print("")
    print("")

### Without Standarization

In [28]:
x = np.array(enbieNeed.iloc[:,:-1])
y = np.array(enbieNeed["target"])

In [29]:
xtr, xts, ytr, yts = train_test_split(x, y, test_size = .18)

#### Hyper-parameter Tuning

In [30]:
from sklearn.model_selection import RandomizedSearchCV

In [31]:
k = round(xtr.shape[0] ** .5)
if k % 2 == 0:
    k+=1
    
n_neighbors = list(range(k-5, k+5))
algo = ["ball_tree", "kd_tree", "brute", "auto"]

paramKNN = {
    "n_neighbors": n_neighbors,
    "algorithm": algo
}

knn = KNeighborsClassifier()
modelKNN = RandomizedSearchCV(estimator= knn, 
                             param_distributions= paramKNN, 
                             cv= 5)

In [32]:
penalty = ["l1", "l2", "elasticnet", "none"]
solver = ["newton-cg", "lbfgs", "liblinear", "sag", "saga"]
max_iter = [1, 10, 100, 1000, 10000]

paramLore = {
    "penalty": penalty,
    "solver": solver,
    "max_iter" : max_iter
}

lore = LogisticRegression()
modelLore = RandomizedSearchCV(estimator= lore, 
                             param_distributions= paramLore, 
                             cv= 5)

In [43]:
n_estimators = list(range(10, 100, 5))
max_features = ['auto', 'sqrt']
min_samples_split = [2, 5, 10]
min_samples_leaf = [1, 2, 4]
bootstrap = [True, False]

paramRFC = {'n_estimators': n_estimators,
               'max_features': max_features,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
               'bootstrap': bootstrap}

rfc = RandomForestClassifier()
modelRFC = RandomizedSearchCV(estimator= rfc, 
                             param_distributions= paramRFC, 
                             cv= 5)

In [34]:
models = [modelKNN, modelLore, modelRFC]

for i in models:
    scoring(i, xtr, ytr, xts, yts)

Model:  RandomizedSearchCV(cv=5, error_score=nan,
                   estimator=KNeighborsClassifier(algorithm='auto',
                                                  leaf_size=30,
                                                  metric='minkowski',
                                                  metric_params=None,
                                                  n_jobs=None, n_neighbors=5,
                                                  p=2, weights='uniform'),
                   iid='deprecated', n_iter=10, n_jobs=None,
                   param_distributions={'algorithm': ['ball_tree', 'kd_tree',
                                                      'brute', 'auto'],
                                        'n_neighbors': [84, 85, 86, 87, 88, 89,
                                                        90, 91, 92, 93]},
                   pre_dispatch='2*n_jobs', random_state=None, refit=True,
                   return_train_score=False, scoring=None, verbose=0)
Best Parameters:  {'n_neighbors': 86, 'algorithm': 'auto'}
Balanced Accuracy Score:  0.6031527675878373
Precision Score:  0.8571428571428571
Recall:  0.20689655172413793
F1 Score:  0.33333333333333326
ROC AUC Score:  0.6031527675878373

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:532: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details:
ValueError: Solver newton-cg supports only 'l2' or 'none' penalties, got l1 penalty.

  warnings.warn("Estimator fit failed. The score on this train-test"
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:532: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details:
ValueError: Solver lbfgs supports only 'l2' or 'none' penalties, got elasticnet penalty.

  warnings.warn("Estimator fit failed. The score on this train-test"
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:532: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details:
ValueError: Only 'saga' solver supports elasticnet penalty, got solver=liblinear.

  warnings.warn("Estimator fit failed. The score on this train-test"
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:532: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details:
ValueError: Solver lbfgs supports only 'l2' or 'none' penalties, got l1 penalty.

  warnings.warn("Estimator fit failed. The score on this train-test"
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:532: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details:
ValueError: penalty='none' is not supported for the liblinear solver

  warnings.warn("Estimator fit failed. The score on this train-test"
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:532: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details:
ValueError: Solver sag supports only 'l2' or 'none' penalties, got elasticnet penalty.

  warnings.warn("Estimator fit failed. The score on this train-test"
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/linear_model/_sag.py:329: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/linear_model/_sag.py:329: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/linear_model/_sag.py:329: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/linear_model/_sag.py:329: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/linear_model/_sag.py:329: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "

Model:  RandomizedSearchCV(cv=5, error_score=nan,
                   estimator=LogisticRegression(C=1.0, class_weight=None,
                                                dual=False, fit_intercept=True,
                                                intercept_scaling=1,
                                                l1_ratio=None, max_iter=100,
                                                multi_class='auto', n_jobs=None,
                                                penalty='l2', random_state=None,
                                                solver='lbfgs', tol=0.0001,
                                                verbose=0, warm_start=False),
                   iid='deprecated', n_iter=10, n_jobs=None,
                   param_distributions={'max_iter': [1, 10, 100, 1000, 10000],
                                        'penalty': ['l1', 'l2', 'elasticnet',
                                                    'none'],
                                        'solver': ['newton-cg', 'lbfgs',
                                                   'liblinear', 'sag',
                                                   'saga']},
                   pre_dispatch='2*n_jobs', random_state=None, refit=True,
                   return_train_score=False, scoring=None, verbose=0)
Best Parameters:  {'solver': 'newton-cg', 'penalty': 'l2', 'max_iter': 100}
Balanced Accuracy Score:  0.6703452351838266
Precision Score:  0.5882352941176471
Recall:  0.3448275862068966
F1 Score:  0.4347826086956522
ROC AUC Score:  0.6703452351838265


Model:  RandomizedSearchCV(cv=5, error_score=nan,
                   estimator=RandomForestClassifier(bootstrap=True,
                                                    ccp_alpha=0.0,
                                                    class_weight=None,
                                                    criterion='gini',
                                                    max_depth=None,
                                                    max_features='auto',
                                                    max_leaf_nodes=None,
                                                    max_samples=None,
                                                    min_impurity_decrease=0.0,
                                                    min_impurity_split=None,
                                                    min_samples_leaf=1,
                                                    min_samples_split=2,
                                                    min_weight_fraction_leaf=0.0,
                                                    n_estimators=100,
                                                    n_jobs...
                                                    warm_start=False),
                   iid='deprecated', n_iter=10, n_jobs=None,
                   param_distributions={'bootstrap': [True, False],
                                        'max_features': ['auto', 'sqrt'],
                                        'min_samples_leaf': [1, 2, 4],
                                        'min_samples_split': [2, 5, 10],
                                        'n_estimators': [10, 15, 20, 25, 30, 35,
                                                         40, 45, 50, 55, 60, 65,
                                                         70, 75, 80, 85, 90,
                                                         95]},
                   pre_dispatch='2*n_jobs', random_state=None, refit=True,
                   return_train_score=False, scoring=None, verbose=0)
Best Parameters:  {'n_estimators': 65, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': False}
Balanced Accuracy Score:  1.0
Precision Score:  1.0
Recall:  1.0
F1 Score:  1.0
ROC AUC Score:  1.0

##### YANG TERPILIH ADALAH MODEL RFC

In [35]:
IBLNeed = aibiel[["Age", "Height", "Weight", "Avg Points", "Avg Rebounds"]]
IBLNeed

   Age  Height  Weight  Avg Points  Avg Rebounds
0   24     190      90           7             6
1   21     185      86           6             3
2   23     178      83          10             3
3   26     185      75          11             4
4   20     183      80           5             2
5   21     191      85           4            10
6   25     188      90           7             5
7   23     179      87           1             2
8   21     177      80           9             8
9   24     182      85           6             5

In [36]:
aibiel["Rekomendasi"] = modelRFC.predict(IBLNeed)
aibiel

,Name,Club,Country,Age,Height,Weight,Avg Points,Avg Rebounds,Rekomendasi
0,Andakara Prastawa Dyaksa,Pelita Jaya Bakrie,Indonesia,24,190,90,7,6,1
1,Reggie Mononimbar,Pelita Jaya Bakrie,Indonesia,21,185,86,6,3,1
2,Hardianus Lakudu,Satria Muda Pertamina Jakarta,Indonesia,23,178,83,10,3,0
3,Kevin Yonas Sitorus,Satria Muda Pertamina Jakarta,Indonesia,26,185,75,11,4,0
4,Arki Dikania Wisnu,Satria Muda Pertamina Jakarta,Indonesia,20,183,80,5,2,0
5,Laurentius Steven Oei,Satria Muda Pertamina Jakarta,Indonesia,21,191,85,4,10,0
6,Mei Joni,Stapac,Indonesia,25,188,90,7,5,1
7,Vincent Rivaldi,Stapac,Indonesia,23,179,87,1,2,0
8,Hardian Wicaksono,Pacific Caesar Surabaya,Indonesia,21,177,80,9,8,0
9,Brandon Jawato,Louvre Surabaya,Indonesia,24,182,85,6,5,1

Nama yang direkomendasikan adalah : Andakara, Reggie, Mei, dan Brandon

### With Standarization

In [54]:
from sklearn.preprocessing import StandardScaler
stds = StandardScaler()
dataSTD = stds.fit_transform(enbieNeed.iloc[:,1:]) #exclude target
dataSTD

array([[-0.57899275, -0.80260413, -0.58938997, -0.74785002, -0.14277326],
       [ 1.06312962,  0.43960663, -1.31961423, -1.10871173, -0.14277326],
       [ 0.78944256,  0.43960663, -0.60637193, -0.78794577, -0.14277326],
       ...,
       [ 2.15787786,  1.50435871, -0.69128173,  0.7757883 , -0.14277326],
       [ 1.06312962,  0.61706531,  0.02196056,  1.37722448, -0.14277326],
       [ 0.24206844,  0.08468927,  1.29560752,  1.17674575, -0.14277326]])

In [55]:
x = dataSTD
y = np.array(enbieNeed["target"])

In [56]:
xtr, xts, ytr, yts = train_test_split(x, y, test_size = .18)

In [57]:
k = round(xtr.shape[0] ** .5)
if k % 2 == 0:
    k+=1
    
n_neighbors = list(range(k-5, k+5))
algo = ["ball_tree", "kd_tree", "brute", "auto"]

paramKNN = {
    "n_neighbors": n_neighbors,
    "algorithm": algo
}
paramKNN

knn = KNeighborsClassifier()
modelKNN = RandomizedSearchCV(estimator= knn, 
                             param_distributions= paramKNN, 
                             cv= 5)

In [58]:
penalty = ["l1", "l2", "elasticnet", "none"]
solver = ["newton-cg", "lbfgs", "liblinear", "sag", "saga"]
max_iter = [1, 10, 100, 1000, 10000]

paramLore = {
    "penalty": penalty,
    "solver": solver,
    "max_iter" : max_iter
}
paramLore

lore = LogisticRegression()
modelLore = RandomizedSearchCV(estimator= lore, 
                             param_distributions= paramLore, 
                             cv= 5)

In [59]:
n_estimators = list(range(10, 100, 5))
max_features = ['auto', 'sqrt']
min_samples_split = [2, 5, 10]
min_samples_leaf = [1, 2, 4]
bootstrap = [True, False]

paramRFC = {'n_estimators': n_estimators,
               'max_features': max_features,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
               'bootstrap': bootstrap}

rfc = RandomForestClassifier()
modelRFC = RandomizedSearchCV(estimator= rfc, 
                             param_distributions= paramRFC, 
                             cv= 5)

In [60]:
models = [modelKNN, modelLore, modelRFC]

for i in models:
    scoring(i, xtr, ytr, xts, yts)

Model:  RandomizedSearchCV(cv=5, error_score=nan,
                   estimator=KNeighborsClassifier(algorithm='auto',
                                                  leaf_size=30,
                                                  metric='minkowski',
                                                  metric_params=None,
                                                  n_jobs=None, n_neighbors=5,
                                                  p=2, weights='uniform'),
                   iid='deprecated', n_iter=10, n_jobs=None,
                   param_distributions={'algorithm': ['ball_tree', 'kd_tree',
                                                      'brute', 'auto'],
                                        'n_neighbors': [84, 85, 86, 87, 88, 89,
                                                        90, 91, 92, 93]},
                   pre_dispatch='2*n_jobs', random_state=None, refit=True,
                   return_train_score=False, scoring=None, verbose=0)
Best Parameters:  {'n_neighbors': 86, 'algorithm': 'ball_tree'}
Balanced Accuracy Score:  1.0
Precision Score:  1.0
Recall:  1.0
F1 Score:  1.0
ROC AUC Score:  1.0

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:532: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details:
ValueError: Solver lbfgs supports only 'l2' or 'none' penalties, got elasticnet penalty.

  warnings.warn("Estimator fit failed. The score on this train-test"
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:532: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details:
ValueError: Solver sag supports only 'l2' or 'none' penalties, got l1 penalty.

  warnings.warn("Estimator fit failed. The score on this train-test"
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:938: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:938: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:938: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:938: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:938: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:532: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details:
ValueError: Solver newton-cg supports only 'l2' or 'none' penalties, got elasticnet penalty.

  warnings.warn("Estimator fit failed. The score on this train-test"
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:532: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details:
ValueError: Solver newton-cg supports only 'l2' or 'none' penalties, got l1 penalty.

  warnings.warn("Estimator fit failed. The score on this train-test"
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:532: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details:
ValueError: Solver sag supports only 'l2' or 'none' penalties, got l1 penalty.

  warnings.warn("Estimator fit failed. The score on this train-test"
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/linear_model/_sag.py:329: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/linear_model/_sag.py:329: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/linear_model/_sag.py:329: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/linear_model/_sag.py:329: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:532: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details:
ValueError: Solver lbfgs supports only 'l2' or 'none' penalties, got l1 penalty.

  warnings.warn("Estimator fit failed. The score on this train-test"

Model:  RandomizedSearchCV(cv=5, error_score=nan,
                   estimator=LogisticRegression(C=1.0, class_weight=None,
                                                dual=False, fit_intercept=True,
                                                intercept_scaling=1,
                                                l1_ratio=None, max_iter=100,
                                                multi_class='auto', n_jobs=None,
                                                penalty='l2', random_state=None,
                                                solver='lbfgs', tol=0.0001,
                                                verbose=0, warm_start=False),
                   iid='deprecated', n_iter=10, n_jobs=None,
                   param_distributions={'max_iter': [1, 10, 100, 1000, 10000],
                                        'penalty': ['l1', 'l2', 'elasticnet',
                                                    'none'],
                                        'solver': ['newton-cg', 'lbfgs',
                                                   'liblinear', 'sag',
                                                   'saga']},
                   pre_dispatch='2*n_jobs', random_state=None, refit=True,
                   return_train_score=False, scoring=None, verbose=0)
Best Parameters:  {'solver': 'lbfgs', 'penalty': 'l2', 'max_iter': 1000}
Balanced Accuracy Score:  1.0
Precision Score:  1.0
Recall:  1.0
F1 Score:  1.0
ROC AUC Score:  1.0


Model:  RandomizedSearchCV(cv=5, error_score=nan,
                   estimator=RandomForestClassifier(bootstrap=True,
                                                    ccp_alpha=0.0,
                                                    class_weight=None,
                                                    criterion='gini',
                                                    max_depth=None,
                                                    max_features='auto',
                                                    max_leaf_nodes=None,
                                                    max_samples=None,
                                                    min_impurity_decrease=0.0,
                                                    min_impurity_split=None,
                                                    min_samples_leaf=1,
                                                    min_samples_split=2,
                                                    min_weight_fraction_leaf=0.0,
                                                    n_estimators=100,
                                                    n_jobs...
                                                    warm_start=False),
                   iid='deprecated', n_iter=10, n_jobs=None,
                   param_distributions={'bootstrap': [True, False],
                                        'max_features': ['auto', 'sqrt'],
                                        'min_samples_leaf': [1, 2, 4],
                                        'min_samples_split': [2, 5, 10],
                                        'n_estimators': [10, 15, 20, 25, 30, 35,
                                                         40, 45, 50, 55, 60, 65,
                                                         70, 75, 80, 85, 90,
                                                         95]},
                   pre_dispatch='2*n_jobs', random_state=None, refit=True,
                   return_train_score=False, scoring=None, verbose=0)
Best Parameters:  {'n_estimators': 65, 'min_samples_split': 2, 'min_samples_leaf': 2, 'max_features': 'auto', 'bootstrap': False}
Balanced Accuracy Score:  1.0
Precision Score:  1.0
Recall:  1.0
F1 Score:  1.0
ROC AUC Score:  1.0

##### Menggunakan modelRFC sebagai opsi terbaik

In [51]:
iblSTD = stds.fit_transform(IBLNeed)
iblSTD

array([[ 0.63599873,  1.32911403,  1.31632171,  0.14285714,  0.48349378],
       [-0.95399809,  0.25724788,  0.42390021, -0.21428571, -0.72524067],
       [ 0.10599979, -1.24336474, -0.24541591,  1.21428571, -0.72524067],
       [ 1.69599661,  0.25724788, -2.0302589 ,  1.57142857, -0.32232919],
       [-1.48399703, -0.17149859, -0.91473203, -0.57142857, -1.12815215],
       [-0.95399809,  1.54348727,  0.20079484, -0.92857143,  2.09513971],
       [ 1.16599767,  0.90036757,  1.31632171,  0.14285714,  0.0805823 ],
       [ 0.10599979, -1.02899151,  0.64700558, -2.        , -1.12815215],
       [-0.95399809, -1.45773797, -0.91473203,  0.85714286,  1.28931674],
       [ 0.63599873, -0.38587182,  0.20079484, -0.21428571,  0.0805823 ]])

In [62]:
aibiel["Rekomendasi STD"] = modelRFC.predict(iblSTD)
aibiel

,Name,Club,Country,Age,Height,Weight,Avg Points,Avg Rebounds,Rekomendasi,Rekomendasi STD
0,Andakara Prastawa Dyaksa,Pelita Jaya Bakrie,Indonesia,24,190,90,7,6,1,0
1,Reggie Mononimbar,Pelita Jaya Bakrie,Indonesia,21,185,86,6,3,1,0
2,Hardianus Lakudu,Satria Muda Pertamina Jakarta,Indonesia,23,178,83,10,3,0,0
3,Kevin Yonas Sitorus,Satria Muda Pertamina Jakarta,Indonesia,26,185,75,11,4,0,0
4,Arki Dikania Wisnu,Satria Muda Pertamina Jakarta,Indonesia,20,183,80,5,2,0,0
5,Laurentius Steven Oei,Satria Muda Pertamina Jakarta,Indonesia,21,191,85,4,10,0,0
6,Mei Joni,Stapac,Indonesia,25,188,90,7,5,1,0
7,Vincent Rivaldi,Stapac,Indonesia,23,179,87,1,2,0,0
8,Hardian Wicaksono,Pacific Caesar Surabaya,Indonesia,21,177,80,9,8,0,0
9,Brandon Jawato,Louvre Surabaya,Indonesia,24,182,85,6,5,1,0